#!/bin/bash

a=path

echo "Enter the file $a: "
read a
for x in $a
do
if test -d "$a"
then
  echo "$a is path <<directory>>" >> path.txt
elif test -f "$a"
then
  echo "$a is file " >> file.txt
else
  echo "$a is not directory or file" >> error.txt
fi
done 
